# fly.toml file generated for green-sun-4156 on 2022-07-06T05:58:41+02:00

app = "green-sun-4156"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
